### ISSUE TITLE
glog flag conflict

### ISSUE THREAD

**Issue by hsinhoyeh** [xiocode/weigo#8]
hi, we hit a flag conflict when our code base has already imported github.com/golang/glog.
since you used "github.com/xiocode/glog" which is a forked project from github.com/golang/glog
they share the same flag names by default. so that is what we are now.
https://github.com/xiocode/weigo/blob/master/weibo.go#L19

we can work around this with this simple change:
```
@@ -15,8 +15,8 @@ import (
        "errors"
        "fmt"
        simplejson "github.com/bitly/go-simplejson"
+       log "github.com/golang/glog"
        to "github.com/gosexy/to"
-       log "github.com/xiocode/glog"
```

here is error message:
```
/tmp/go-build275023775/weibo/_test/weibo.test flag redefined: log_dir
panic: /tmp/go-build275023775/weibo/_test/weibo.test flag redefined: log_dir

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc208062060, 0x7faf0f1e0110, 0xc2080cf450, 0xac2b30, 0x7, 0xba04f0, 0x2f)
        /usr/local/go/src/flag/flag.go:679 +0x494
flag.(*FlagSet).StringVar(0xc208062060, 0xc2080cf450, 0xac2b30, 0x7, 0x0, 0x0, 0xba04f0, 0x2f)
        /usr/local/go/src/flag/flag.go:582 +0xcf
flag.(*FlagSet).String(0xc208062060, 0xac2b30, 0x7, 0x0, 0x0, 0xba04f0, 0x2f, 0xc2080cf440)
```

**Comment by xiocode** [comment]
Fixed
